[project]
name = "baynext-api"
version = "0.1.0"
description = "Baynext API for managing datasets, jobs, and pipelines"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "psycopg2-binary>=2.9.10",
    "pydantic-settings>=2.9.0",
    "python-multipart>=0.0.20",
    "requests>=2.32.3",
    "sqlmodel>=0.0.24",
    "supabase>=2.18.0",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "pytest-asyncio>=0.26.0",
    "pytest-cov>=6.1.1",
    "pytest-env>=1.1.5",
]

[tool.ruff.lint.isort]
known-local-folder = ["app", "tests"]

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "session"
env = [
    "DATABASE_URL=postgresql://user:password@host:80/dbname",
    "AUTH_SECRET=auth_secret",
    "BUCKET_NAME=bucket_name",
]
